---
- hosts: all
  serial: 1
  gather_facts: False
  vars:
    target_hostname: "{{ inventory_hostname }}"
    infoblox_gridmaster: "{{ infoblox_gridmaster }}"
    infoblox_username: "{{ infoblox_username }}"
    infoblox_password: "{{ infoblox_password }}"
  pre_tasks:
    - debug: var=target_hostname
    - set_fact:
        target_cidr: "10.10.1.0/24"
        target_fqdn: "{{target_hostname}}.qa.example.com"
      when: target_hostname | search("^qa_.*")
    - set_fact:
        target_cidr: "10.10.2.0/24"
        target_fqdn: "{{target_hostname}}.test.example.com"
      when: target_hostname | search("^test_.*")
    - set_fact:
        target_cidr: "10.10.3.0/24"
        target_fqdn: "{{target_hostname}}.prod.example.com"
      when: target_hostname | search("^production_.*")
    - debug: var=target_fqdn
    - debug: var=target_cidr

  roles:
    - role: infoblox_add_host


