---
- hosts: localhost
  serial: 1
  gather_facts: False
  vars:
    target_fqdn: {{ inventory_hostname }}
    infoblox_gridmaster: {{ infoblox_gridmaster }}
    infoblox_username: {{ infoblox_username }}
    infoblox_password: {{ infoblox_password }}
  tasks:    
    - set_fact: target_cidr="10.10.1.0/24"
      when: target_fqdn | search("^qa_.*")
      register: target_cidr
    - set_fact: target_cidr="10.10.2.0/24"
      when: target_fqdn | search("^test_.*")
      register: target_cidr
    - set_fact: target_cidr="10.10.3.0/24"
      when: target_fqdn | search("^production_.*")
      register: target_cidr      

  roles:
    - role: infoblox_add_host


