---
- hosts: all
  tasks:
  - name: Set hostname
    hostname: name='{{ inventory_hostname }}'
  - name: Install Cert
    command: "/usr/bin/yum -y localinstall http://sat.example.com/pub/katello-ca-consumer-latest.noarch.rpm"
  - name: Register with Satellite
    command: "/usr/sbin/subscription-manager register --org Default_Organization --force --activationkey rhel7"
    register: registered
  - name: Enable Repositories
    command: subscription-manager repos --enable=rhel-7-server-satellite-tools-6.2-rpms
    when: registered|success
  - name: Install Katello Agent
    yum: pkg=katello-agent state=latest
    when: registered|success
    notify:
    - Enable Katello Agent
    - Start Katello Agent
  - name: Install Puppet
    yum: pkg=puppet state=latest
    when: registered|success
    register: puppet_installed
    notify:
    - Enable Puppet
  - name: Configure Puppet Agent Server
    command: "/usr/bin/puppet config set server sat.example.com --section agent"
    when: puppet_installed|success
  - name: Configure Puppet Agent Client Name
    command: "/usr/bin/puppet config --section main set certname {{ inventory_hostname }}"
    when: puppet_installed|success
  - name: Configure Puppet Agent Environment
    command: "/usr/bin/puppet config --section agent set environment KT_Default_Organization_Library_RHEL7_3"
    when: puppet_installed|success
  - name: Run Puppet Test
    command: "/usr/bin/puppet agent --test --noop --onetime --waitforcert 60"
    when: puppet_installed|success
  - name: Apply Puppet
    command: "/usr/bin/puppet agent -t --server sat.example.com"
    when: puppet_installed|success
    ignore_errors: yes
  - name: Start Puppet
    service: name=puppet state=started
  - name: Update all packages
    command: "/usr/bin/yum -y update -x kernel"
  handlers:
  - name: Enable Katello Agent
    service: name=goferd enabled=yes
  - name: Start Katello Agent
    service: name=goferd state=started
  - name: Enable Puppet
    service: name=puppet enabled=yes
