---
- name: Add Disk to RHV VM
  hosts: localhost
  connection: local
  #vars_files:
  #  - "../group_vars/all/rhv-vars"
  tasks:
    - debug: var=manageiq
    - debug: var=manageiq.api_url
    - debug: var=manageiq.api_token
    - debug: var=manageiq.service
    - debug: var=manageiq.event_target
    - debug: var=url
    - debug: var=username
    - debug: var=password
    - debug: var=vm_id

    - block:
        - name: Obtain SSO token
          no_log: false
          ovirt_auth:
            url: "{{ url }}"
            username: "{{ username }}"
            password: "{{ password }}"
            insecure: true
            #ca_file: "/usr/local/readablebytower/ovirt-ca.pem"
        - name: Create and attach new disk to VM
          ovirt_disks:
            name: "{{ vm_id }}_data_disk"
            vm_id: "{{ vm_id }}"
            size: "10GiB"
            format: "cow"
            interface: "virtio"
      always:
        - name: Revoke the SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
